import { MateCardData } from "@/types/MateCardData";

export const dummyCards: MateCardData[] = [
  {
    id: 1,
    title: "25일 오늘 제주도 저녁 식사",
    description:
      "오늘 저녁 식사하실분 오늘 저녁 식사하실분 오늘 저녁 식사하실분 오늘 저녁 식사하실분 오늘 저녁 식사하실분 오늘 저녁 식사하실분",
    recruitCount: 3,
    region: "제주도",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "하나",
      age: 28,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.03.25",
      endDate: "2025.03.26",
      durationText: "1일",
    },
  },
  {
    id: 2,
    title: "서울 시티투어 함께 가실 분",
    description: "서울 곳곳을 같이 구경해요",
    recruitCount: 0,
    region: "서울",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "민수",
      age: 31,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.01",
      endDate: "2025.04.02",
      durationText: "1일",
    },
  },
  {
    id: 3,
    title: "부산 야경 드라이브 메이트 구해요",
    description: "부산 야경 보며 산책할 분",
    recruitCount: 1,
    region: "부산",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "지아",
      age: 26,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.05",
      endDate: "2025.04.06",
      durationText: "1일",
    },
  },
  {
    id: 4,
    title: "강릉 바다 보러가요",
    description: "드라이브하면서 강릉 바다 보고 올 사람?",
    recruitCount: 0,
    region: "강릉",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "준호",
      age: 29,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.10",
      endDate: "2025.04.12",
      durationText: "2일",
    },
  },
  {
    id: 5,
    title: "대구 벚꽃 구경 메이트",
    description: "벚꽃 시즌 함께할 사람 구해요!",
    recruitCount: 4,
    region: "대구",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "예린",
      age: 27,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.03",
      endDate: "2025.04.05",
      durationText: "2일",
    },
  },
  {
    id: 6,
    title: "속초 맛집 투어",
    description: "회, 오징어순대 같이 먹을 사람?",
    recruitCount: 0,
    region: "속초",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "현우",
      age: 30,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.15",
      endDate: "2025.04.16",
      durationText: "1일",
    },
  },
  {
    id: 7,
    title: "제주도 카페 투어",
    description: "인스타 핫플 도는 카페 투어 메이트",
    recruitCount: 0,
    region: "제주도",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "소정",
      age: 25,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.20",
      endDate: "2025.04.22",
      durationText: "2일",
    },
  },
  {
    id: 8,
    title: "서울 근교 당일치기 여행",
    description: "서울 근처 드라이브 같이 할 사람",
    recruitCount: 3,
    region: "경기",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "지훈",
      age: 34,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.18",
      endDate: "2025.04.18",
      durationText: "1일",
    },
  },
  {
    id: 9,
    title: "부산 해산물 먹방 투어",
    description: "회/조개구이 같이 먹어요",
    recruitCount: 2,
    region: "부산",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "슬기",
      age: 30,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.25",
      endDate: "2025.04.26",
      durationText: "1일",
    },
  },
  {
    id: 10,
    title: "전주 한옥마을 전통 체험",
    description: "한복입고 사진 찍을 메이트",
    recruitCount: 3,
    region: "전주",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "유진",
      age: 26,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.04.28",
      endDate: "2025.04.29",
      durationText: "1일",
    },
  },
  {
    id: 11,
    title: "25일 제주도 저녁 식사",
    description: "같이 밥 먹어요!",
    recruitCount: 0,
    region: "제주도",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "유저1",
      age: 21,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.03.25",
      endDate: "2025.03.26",
      durationText: "당일",
    },
  },
  {
    id: 12,
    title: "27일 서울 시티투어",
    description: "서울 구경 같이 해요",
    recruitCount: 3,
    region: "서울",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "유저2",
      age: 22,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.03.27",
      endDate: "2025.03.29",
      durationText: "2일",
    },
  },
  {
    id: 13,
    title: "29일 부산 야경 드라이브",
    description: "드라이브할 분 구해요",
    recruitCount: 1,
    region: "부산",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "유저3",
      age: 24,
      gender: "남",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.03.29",
      endDate: "2025.03.29",
      durationText: "당일",
    },
  },
  {
    id: 14,
    title: "2일 부산 카페 탐방",
    description: "감성 카페 모음",
    recruitCount: 2,
    region: "전주",
    thumbnailUrl: "/jeju.jpg",
    user: {
      name: "유저20",
      age: 28,
      gender: "여",
      imageUrl: "/default-profile.png",
    },
    period: {
      startDate: "2025.05.02",
      endDate: "2025.05.03",
      durationText: "당일",
    },
  },
];
